mysite/appointment/urls.py
from django.contrib import admin
from django.urls import path
from appointment.views import reserve, confirm_reserve, cancel_reserve
from django.views.generic import TemplateView

app_name = 'appointment'

urlpatterns = [
    path('<int:barber_id>/', reserve, name = 'reserve'),
    path('confirm/<int:barber_id>/<str:date>', confirm_reserve, name = 'confirm_reserve'),
    path('cancel/<str:cancel_uuid>/', cancel_reserve, name = 'cancel_reserve'),
]

mysite/main/urls.py
from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path('', index, name = 'index'),
]

mysite/main/models.py
from django.db import models

# Create your models here.

mysite/main/views.py
from django.shortcuts import render
from barber.models import Barber
from datetime import datetime

# Create your views here.
def convert(x):
    if x >= 1 and x <= 9:
        return f'0{x}'
    return str(x)

def index(req):
    barbers = Barber.objects.all()
    today = str(datetime.now().year) + '-' + convert(datetime.now().month) + '-' + convert(datetime.now().day)
    max_val = str(datetime.now().year + 1) + '-' + convert(datetime.now().month) + '-' + convert(datetime.now().day)
    return render(req, 'main/index.html', {'barbers': barbers, 'min': today, 'value': today, 'max': max_val})

mysite/main/templates/main/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    {% include 'main/includes/navbar.html' %}
    {% include 'main/includes/messages.html' %}
    {% block body %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script>
        window.onload = (event) => {
            let myAlert = document.querySelector('.toast');
            let bsAlert = new bootstrap.Toast(myAlert);
            bsAlert.show();
        }
        const myModal = document.getElementById('myModal')
        const myInput = document.getElementById('myInput')

        myModal.addEventListener('shown.bs.modal', () => {
            myInput.focus()
        })
    </script>
</body>
</html>

mysite/main/templates/main/error.html
{% extends 'main/base.html' %}

{% block title %}
    Enlace no encontrado
{% endblock %}

{% block body %}
<h1>
    URL NO ENCONTRADA o TOKEN EXPIRADO!
</h1>
<h2>
    Intenta de nuevo!
</h2>
{% endblock %}

mysite/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
    Chevalier
{% endblock %}

{% block body %}
<div class="container">
    &nbsp;
    <div class="row">
        {% load static %}
        {% for b in barbers %}
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'media/avatar.jpeg' %}" class="card-img-top" alt="imagen">
                    <div class="card-body">
                        <h5 class="card-title">{{ b.name }} {{ b.lastname1 }}</h5>
                        <p class="card-text">Reserva ya mismo con {{ b.name }}!</p>
                        <form method="POST" action="{% url 'appointment:reserve' b.id %}">
                            {% csrf_token %}
                            <input type="date" name="appointment_date" min="{{ min }}" max="{{ max }}" value="{{ value }}">
                            &nbsp;
                            <button type="submit" class="btn btn-primary">Ver disponibilidad</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}