mysite/barber/urls.py
from django.urls import path
from .views import add_barber, delete_barber, modify_barber, index

app_name = 'barber'

urlpatterns = [
    path('', index, name = 'index'),
    path('add_barber/', add_barber, name = 'add_barber'),
    path('delete_barber/<int:id>/', delete_barber, name = 'delete_barber'),
    path('modify_barber/', modify_barber, name = 'modify_barber'),
]

mysite/main/urls.py
from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path('', index, name = 'index'),
]

mysite/barber/models.py
from django.db import models

# Create your models here.
class Barber(models.Model):
    name = models.CharField(max_length = 100)
    lastname1 = models.CharField(max_length = 100)
    lastname2 = models.CharField(max_length = 100)

    def __str__(self) -> str:
        return f'{self.name} {self.lastname1} {self.lastname2} {self.id}'

mysite/barber/forms.py
from django import forms

class BarberForm(forms.Form):
    name = forms.CharField(max_length = 100, label = 'Nombre', widget = forms.TextInput(
        attrs = {'class': 'form-control'}
    ))
    lastname1 = forms.CharField(max_length = 100, label = 'Apellido paterno', widget = forms.TextInput(
        attrs = {'class': 'form-control'}
    ))
    lastname2 = forms.CharField(max_length = 100, label = 'Apellido materno', widget = forms.TextInput(
        attrs = {'class': 'form-control'}
    ))

class ModifyBarberForm(forms.Form):
    id = forms.IntegerField(label = 'Id', widget = forms.TextInput(
        attrs = {'class': 'form-control'}
    ))
    name = forms.CharField(max_length = 100, label = 'Nombre', widget = forms.TextInput(
        attrs = {'class': 'form-control'}
    ))
    lastname1 = forms.CharField(max_length = 100, label = 'Apellido paterno', widget = forms.TextInput(
        attrs = {'class': 'form-control'}
    ))
    lastname2 = forms.CharField(max_length = 100, label = 'Apellido materno', widget = forms.TextInput(
        attrs = {'class': 'form-control'}
    ))

mysite/barber/views.py
from django.shortcuts import render, redirect
from django.contrib import messages as m
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import requires_csrf_token
from .forms import BarberForm, ModifyBarberForm
from .models import Barber

# Create your views here.
@login_required
def index(req):
    barbers = Barber.objects.all()
    barber_form = BarberForm()
    modify_barber_form = ModifyBarberForm()
    ctx = {'barbers': barbers, 'barber_form': barber_form, 'modify_barber_form': modify_barber_form}
    return render(req, 'barber/barber.html', ctx)

@login_required
@requires_csrf_token
def add_barber(req):
    if req.method == 'POST':
        data = req.POST
        form = BarberForm(data)

        if form.is_valid():
            name = data['name']
            lastname1 = data['lastname1']
            lastname2 = data['lastname2']
            barber = Barber(name = name, lastname1 = lastname1, lastname2 = lastname2)
            barber.save()
            m.info(req, 'Barbero registrado exitosamente!')
            return redirect('barber:index')

        m.error(req, 'No se pudo registrar el barbero')
        return redirect('main:index')

@login_required
@requires_csrf_token
def modify_barber(req):
    if req.method == 'POST':
        data = req.POST
        id = data['id']
        name = data['name']
        lastname1 = data['lastname1']
        lastname2 = data['lastname2']
        
        try:
            barber = Barber.objects.get(id = id)
        except:
            m.error(req, f'Barbero con id {id} no existe')
            return redirect('barber:index')
        
        barber.name = name
        barber.lastname1 = lastname1
        barber.lastname2 = lastname2
        barber.save()

        m.info(req, 'Barbero modificado exitosamente!')
        return redirect('barber:index')

@login_required
@requires_csrf_token
def delete_barber(req, id: int):
    if req.method == 'POST':
        barber = Barber.objects.get(id = id)
        barber.delete()
        m.info(req, 'Barbero eliminado correctamente!')
        return redirect('barber:index')

mysite/barber/templates/barber/add_barber.html
{% extends 'main/base.html' %}

{% block title %}
Añadir barbero
{% endblock %}

{% block body %}
<form method = "POST" action="{% url 'barber:add_barber' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Agregar</button>
</form>
{% endblock %}

mysite/barber/templates/barber/barber.html
{% extends 'main/base.html' %}

{% block title %}
Barberos
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-3">
            <h2>Barberos</h2>
            <ul class="list-group">
                {% for barber in barbers %}
                    <li class="list-group-item">
                        Nombre Completo: {{ barber.name }} {{ barber.lastname1 }} {{ barber.lastname2 }}
                        <br/>
                        Id: {{ barber.id }}
                        <form method="POST" action="{% url 'barber:delete_barber' barber.id %}">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-sm" type="submit">Eliminar</button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-3">
            <h2>Agregar barbero</h2>
            <form method="POST" action="{% url 'barber:add_barber' %}">
                {% csrf_token %}
                {{ barber_form.as_p }}
                <button type="submit" class="btn btn-primary btn-sm">Agregar barbero</button>
            </form>
        </div>
        <div class="col-3">
            <h2>Modificar barbero</h2>
            <form method="POST" action="{% url 'barber:modify_barber' %}">
                {% csrf_token %}
                {{ modify_barber_form.as_p }}
                <button type="submit" class="btn btn-primary btn-sm">Modificar barbero</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}