mysite/barber/urls.py
from django.urls import path
from .views import add_barber, delete_barber, modify_barber, index

app_name = 'barber'

urlpatterns = [
    path('', index, name = 'index'),
    path('add_barber/', add_barber, name = 'add_barber'),
    path('delete_barber/<int:id>/', delete_barber, name = 'delete_barber'),
    path('modify_barber/', modify_barber, name = 'modify_barber'),
]

mysite/main/urls.py
from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path('', index, name = 'index'),
]

mysite/user_profile/urls.py
from django.urls import path
from .views import login_req, logout_req

app_name = 'user_profile'

urlpatterns = [
    path('login/', login_req, name = 'login_req'),
    path('logout/', logout_req, name = 'logout_req'),
]

mysite/main/models.py
from django.db import models

# Create your models here.

mysite/main/views.py
from django.shortcuts import render
from barber.models import Barber
from datetime import datetime

# Create your views here.
def convert(x):
    if x >= 1 and x <= 9:
        return f'0{x}'
    return str(x)

def index(req):
    barbers = Barber.objects.all()
    today = str(datetime.now().year) + '-' + convert(datetime.now().month) + '-' + convert(datetime.now().day)
    max_val = str(datetime.now().year + 1) + '-' + convert(datetime.now().month) + '-' + convert(datetime.now().day)
    return render(req, 'main/index.html', {'barbers': barbers, 'min': today, 'value': today, 'max': max_val})

mysite/main/templates/main/includes/messages.html
{% for m in messages %}
    {% if m.tags == 'error' %}
        <div class="toast-container top-12 end-0 p-1">
            <div class="toast align-items-center text-bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ m }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>
    {% endif %}
    {% if m.tags == 'success' %}
        <div class="toast-container top-12 end-0 p-1">
            <div class="toast align-items-center text-bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ m }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>
    {% endif %}
    {% if m.tags == 'info' %}
        <div class="toast-container top-12 end-0 p-1">
            <div class="toast align-items-center text-bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ m }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>
    {% endif %}
    {% if m.tags == 'warning' %}
        <div class="toast-container top-12 end-0 p-1">
            <div class="toast align-items-center text-bg-warning border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ m }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}

mysite/main/templates/main/includes/navbar.html
{% block body %}
<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="{% url 'main:index' %}">Chevalier</a>
        {% if not user.is_authenticated and not login %}
            <a class="nav-link active text-white" aria-current="page" href="{% url 'user_profile:login_req' %}">Acceder</a>
        {% endif %}
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active text-white" aria-current="page" href="{% url 'barber:index' %}">Gestionar barberos</a>
                    </li>
                </ul>
            </div>
            <a class="nav-link active text-white" aria-current="page" href="{% url 'user_profile:logout_req' %}">Cerrar Sesión</a>
        {% endif %}
    </div>
</nav>
{% endblock %}